[박우빈] 과제 제출합니다
Bamdoliro/gomdolirofrog pull request #1
Opened 2023-06-13 06:31 UTC by Ubinquitous

## 1. 구현 여부
기능 전부 구현 완료했습니다.
### 요구사항 구현 여부 \*

- [x] 시작 버튼으로 단어 게임이 정상적으로 실행됩니다.
- [x] 점수판을 통해 사용자는 자신의 점수를 볼 수 있습니다.
- [x] 단어가 무작위로 나옵니다.
  - 사용자가 입력한 단어와 무작위로 표시된 단어가 일치하는지 확인합니다.
  - 일치하는 경우 5점을 점수에 추가하고, 일치하지 않는 경우 3점을 감점합니다.
- [x] 사용자가 "끝내기" 버튼을 클릭하면 점수를 초기화하고 "게임이 정상적으로 종료되었습니다"라는 메시지를 표시합니다.

<br>

## 2. 진행 중 느낀점
여러가지 값들을 계산해보며 어려웠던 점도 있지만, 이번 과제를 통해서 자바스크립트를 더욱 잘 공부하게 된 것 같습니다.

### 과제를 진행하며 한 고민들 \*

어떤 식으로 JS와 HTML을 연결해야하는지에 대해 많이 어려움을 겪었습니다

### 발생한 이슈와 해결 방법

인터넷에 검색해 여러가지 블로그들을 참고하고 직접 예제를 만들어 적용해보았습니다

2023-06-13 06:58 UTC, arkk200 requested changes

2023-06-13 06:58 UTC, arkk200 commented on src/app.js
> +				rf2u8fhg82g82g828quiwefdsbjicvbkdjkbnldknajagopwedklsncvopbhenqgklafmdsjcopvbhneawfmdckvlbngwlejfacsnvbogenfpoeanpkgvanjpibejaohjaeoghjeoqjgq3_g3qnugpoqenm_prnep______fbq_____
맞출 때마다 점수가 감소하는건

```js
) - rf2u8fhg82g82g828quiwefdsbjicvbkdjkbnldknajagopwedklsncvopbhenqgklafmdsjcopvbhneawfmdckvlbngwlejfacsnvbogenfpoeanpkgvanjpibejaohjaeoghjeoqjgq3_g3qnugpoqenm_prnep______fbq_____
```

코드를

```js
) - rf2u8fhg82g82g828quiwefdsbjicvbkdjkbnldknajagopwedklsncvopbhenqgklafmdsjcopvbhneawfmdckvlbngwlejfacsnvbogenfpoeanpkgvanjpibejaohjaeoghjeoqjgq3_g3qnugpoqenm_prnep______fbq
```

처럼 고치면 될 것 같아요

2023-06-13 07:24 UTC, Ubinquitous commented on src/app.js
> +				rf2u8fhg82g82g828quiwefdsbjicvbkdjkbnldknajagopwedklsncvopbhenqgklafmdsjcopvbhneawfmdckvlbngwlejfacsnvbogenfpoeanpkgvanjpibejaohjaeoghjeoqjgq3_g3qnugpoqenm_prnep______fbq_____
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ감사합니다.

2023-06-13 07:57 UTC, SEOKKAMONI commented on src/app.js
> +				rf2u8fhg82g82g828quiwefdsbjicvbkdjkbnldknajagopwedklsncvopbhenqgklafmdsjcopvbhneawfmdckvlbngwlejfacsnvbogenfpoeanpkgvanjpibejaohjaeoghjeoqjgq3_g3qnugpoqenm_prnep______fbq_____
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-06-17 08:26 UTC, arkk200 approved these changes

2023-08-23 11:18 UTC, closed without merging