[이지우] 과제 제출합니다
Bamdoliro/gomdolirofrog pull request #4
Opened 2023-06-26 14:35 UTC by E-jiwoo

## 1. 구현 여부

### 요구사항 구현 여부 \*

- [x] 시작 버튼으로 단어 게임이 정상적으로 실행됩니다.
- [x] 점수판을 통해 사용자는 자신의 점수를 볼 수 있습니다.
- [x] 단어가 무작위로 나옵니다.
  - 사용자가 입력한 단어와 무작위로 표시된 단어가 일치하는지 확인합니다.
  - 일치하는 경우 5점을 점수에 추가하고, 일치하지 않는 경우 3점을 감점합니다.
- [x] 사용자가 "끝내기" 버튼을 클릭하면 점수를 초기화하고 "게임이 정상적으로 종료되었습니다"라는 메시지를 표시합니다.

<br>

## 2. 진행 중 느낀점

 처음에 이 과제를 받았을 때는 쉽게 해낼 수 있겠다라고 생각하였습니다. 하지만 저에게는 쉬운 과제가 아니였었나봅니다.. 저는 그 어떤 순간보다도 이번 과제를 하며 구글링을 가장 많이 해보았던 것 같습니다. 그 순간들 덕분에 js에 대해 조금씩 알아갈 수 있었습니다. 한 번 git을 잘 못하여 갈아엎기도 하고 잘 안 풀리는 코드들로 인해 몇 시간을 끙끙 앓아서 힘들었었는데 여러 방법들을 해보다가 해결이 되었을 때는 정말 행복하였습니다. 이번 과제를 진행하면서 한 편으로는 힘들었지만 다른 한 편으로는 행복한 시간을 보낼 수 있었습니다.    

### 과제를 진행하며 한 고민들 \*

-  중첩함수와 while을 쓰는 방법은 없을까에 대해 고민하였습니다. button을 입력받았을 때 inputAnswer부분의 함수를 실행시킬 때 중첨함수를 사용해보려 했지만 잘 되지 않았습니다. 또한 while를 무작위 단어를 받고 입력하고 점수를 받고 이를 반복하는 코드에 사용하고 싶었지만 잘 되지 않았습니다.  그래서 이를 사용하기 위해 구글링을 하며 찾아보며 고민을 해보았었습니다.  

### 발생한 이슈와 해결 방법

- script부분을 app.js를 불러와서 실행시키니 사용되지 않는 함수들이 생기게 되었었습니다. 그리하여 index.html의 script부분에 적어서 실행하였습니다
- import하여 words.mjs를 불러오지 못하였습니다(외부 모듈을 불러 올 수 없다고 떴습니다) npm init을 하여 package.jason부분을 추가해보아도 안되어서 이 또한 index.html의 script부분에 적어서 실행하였습니다.  

### 질문

- 저는 위에서 발생한 이슈들을 해결하여 실행시키기보다는 다른 방법을 통하여 실행이 되도록 하였습니다. 그렇기에 위의 이슈들을 해결하는 방법에 대해 알고 싶습니다. 특히 script부분에 js코드를 적어서 실행시켰을 때는 실행이 되었던 함수가 app.js를 불러와서 할  때에는 함수 불투명하게 뜬 후 마우스 커서를 가까이 대면 "선언은 되었지만 해당 값이 읽히지는 않았습니다" 라고 뜨고 왜 함수가 실행이 안 되는지 궁금합니다

2023-07-07 01:03 UTC, SEOKKAMONI reviewed
너무 수고하셨습니다 ~~ !! 방학하면 인턴 과제 나갈거니깐 기다리세욥 !!

2023-07-07 01:03 UTC, SEOKKAMONI commented on index.html
> +        "zebra"];
data는 따로 파일을 분리하여 import시키는 방법이 더 좋을것같습니다 ~

https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/import

2023-07-07 01:03 UTC, SEOKKAMONI commented on index.html
> +        var n=0;
https://bbubbush.tistory.com/47

var는 다양한 문제 때문에 사용하지 않는게 가장 좋습니다

변수를 선언하고싶다면 let은 어떨까요?

2023-07-07 01:03 UTC, SEOKKAMONI commented on index.html
> +            document.getElementById("score").innerHTML = score;
innerHTML은 HTML의 요소까지 변경하고 싶을때 사용하는것이 좋습니다 

안에 있는 text만 변경하고 싶은거라면 textContent나 innerText를 사용하는것은 어떨까요?

2023-07-07 01:03 UTC, SEOKKAMONI commented on index.html
> +            document.getElementById("word").innerHTML=word;
위와 마찬가지입니다 ~

2023-07-07 01:03 UTC, SEOKKAMONI commented on index.html
> +            if(n==1){
```suggestion
            if(n===1){
```

이부분만 동등연산자인데 이유가 따로 있는건가요?

2023-07-07 01:03 UTC, SEOKKAMONI commented on style.css
> -    box-sizing: border-box;
css 전역으로 기본 세팅 해주신거 너무 좋은데 따로 지우신 이유가 있나요?

2023-07-07 01:39 UTC, arkk200 requested changes

2023-07-07 01:39 UTC, arkk200 commented on index.html
> +        const _words = ["apple",
변수명 앞에 언더바를 붙이 이유가 무엇인가요?

2023-07-07 01:39 UTC, arkk200 commented on index.html
> +        var n=0;
```suggestion
        var n = 0;
```
처럼 변수명과 대입 연산자, 값 사이에는 공백을 한 칸 주는게 관용적인 것 같아요.
모던 자바스크립트에 [코드스타일](https://ko.javascript.info/coding-style) 챕터를 한 번 읽어보는게 좋을 것 같습니다.

2023-07-10 23:27 UTC, E-jiwoo commented on index.html
> +        const _words = ["apple",
js파일을 구분지어 import를 시도했을 때 import words from "../data/words.mjs"; 를 사용하면 해당 문장이 불투명하게 바뀌며 사용하지 않은 선언이라는 문장이 되었는데 import _words from "../data/words.mjs"; 로 변수명을 다르게 하니 불투명하던 문장이 다시 살아나게 되었었어서 import할 때 변수명을 바꾸어 코드를 작성했었습니다. 그때 바꾼 변수명이 script 부분에 js파일에 있던 코드를 붙여넣기 할 때 그대로 바꾸어져 있는 것입니다.

2025-04-19 16:39 UTC, closed without merging